name: Test PR Labeler Action

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        
        - name: Add Single Label Test
          uses: ./
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LABELS_TO_ADD: bug

        - name: Remove Single Label Test
          uses: ./
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LABELS_TO_REMOVE: bug

        - name: Add and Remove Single Label Test
          uses: ./
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LABELS_TO_ADD: bug
            LABELS_TO_REMOVE: enhancement

        - name: Add and Remove Multiple Labels Test
          uses: ./
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LABELS_TO_ADD: bug,feature
            LABELS_TO_REMOVE: enhancement,duplicate
